INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr. Chocolate", 1, "male", "chocolate brown", "sweet", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Rowdy", 2, "male", "striped", "rambunctious", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Tabitha", 3, "female", "satin brown", "very nice", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Sergeant Brown", 4, "female", "night sky black", "regal", 1)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ()